import Head from 'next/head';
import ProjectsList from '../src/projects/List';

const Home = () => {
  return (
    <div className='m-2'>
      <Head>
        <title>Pebble</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ProjectsList />
    </div>
  );
};

export default Home;
